language: objective-c
osx_image: xcode9

install:
  - gem install xcpretty

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project FaveButtonDemo/FaveButtonDemo.xcodeproj -scheme "FaveButton" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.0'
      -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c      