language: objective-c
osx_image: xcode9

install:
  - gem install xcpretty

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project FaveButtonDemo/FaveButtonDemo.xcodeproj -scheme "FaveButton" -sdk iphonesimulator10.0 -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.0'
      -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c      